### ISSUE TITLE
misconfiguration in recipe and config

### ISSUE THREAD

**Issue by tacman** [jawira/doctrine-diagram-bundle#58]
Although the installation instructions say to install with --dev, the recipe calls for it to be included in "all".

https://github.com/symfony/recipes-contrib/blob/25b3e874a28b499e486c7eb1f03194749202bba6/jawira/doctrine-diagram-bundle/0.7/manifest.json

In order for to be only in dev, you should also change the package.config in the recipe to

```yaml
# https://github.com/jawira/doctrine-diagram-bundle
when@dev:
    doctrine_diagram:
        size: midi
        filename: database
        format: svg

when@test:
    doctrine_diagram:
        size: midi
        filename: test-database
        format: svg
```

I've included the setup for test as well (since my tests are usually sqlite and production is usually postgres)
